// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalkingStumpShop;

#nullable disable

namespace TalkingStumpShop.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    partial class WebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TalkingStumpShop.Models.NewsArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "Мастерская 'Говорящий Пень' рада представить свою последнюю коллекцию уникальных столов, изготовленных с любовью и профессионализмом. Каждый стол - это настоящее произведение искусства, созданное из натурального дерева и эпоксидной смолы. Наши мастера вложили всю свою страсть и талант в каждый деталь, чтобы создать функциональные и впечатляющие предметы мебели, которые украсят ваш интерьер. Погрузитесь в мир природной красоты и изысканного дизайна с новой коллекцией столов 'Говорящий Пень'.",
                            CreationDate = new DateTime(2023, 11, 7, 18, 14, 59, 174, DateTimeKind.Utc).AddTicks(9074),
                            ImageFileName = "tables-collection.png",
                            Title = "Новое творческое вдохновение: Говорящий Пень представляет уникальные столы из дерева и эпоксидной смолы!"
                        },
                        new
                        {
                            Id = 2L,
                            Content = "С наступлением праздничного сезона мы рады представить вам нашу новую коллекцию эксклюзивных подарков ручной работы. Каждое изделие создано с заботой и вниманием к деталям нашими опытными мастерами. Вы найдете у нас подарки для всех случаев: от деревянных часов до восхитительных ваз и деревянных фигурок. Подарите вашим близким что-то особенное и уникальное в этот праздничный сезон!",
                            CreationDate = new DateTime(2023, 11, 7, 18, 14, 59, 174, DateTimeKind.Utc).AddTicks(9078),
                            ImageFileName = "figure-collection.png",
                            Title = "Эксклюзивные подарки: Говорящий Пень представляет коллекцию деревянных изделий ручной работы"
                        },
                        new
                        {
                            Id = 3L,
                            Content = "Мы рады объявить о запуске наших мастер-классов для всех любителей ручной работы и творчества! Присоединяйтесь к нам, чтобы научиться создавать удивительные изделия из дерева и эпоксидной смолы под руководством опытных мастеров. Эти мастер-классы предоставят вам уникальную возможность погрузиться в мир деревянного искусства и научиться создавать собственные шедевры. Следите за нашими объявлениями для получения дополнительной информации о датах и регистрации!",
                            CreationDate = new DateTime(2023, 11, 7, 18, 14, 59, 174, DateTimeKind.Utc).AddTicks(9081),
                            ImageFileName = "master-class.png",
                            Title = "Мастер-классы от Говорящего Пня: научитесь создавать собственные шедевры из дерева и эпоксидной смолы!"
                        });
                });

            modelBuilder.Entity("TalkingStumpShop.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Этот набор разделочных досок идеален для подготовки пищи с удовольствием. Каждая доска обладает уникальным дизайном, который придает вашей кухне особый шарм. Идеально подходит для настольных приготовлений и подачи блюд. Сделайте свою кухню еще более стильной и функциональной.",
                            ImageFileName = "cutting-board-cats.jpg",
                            Name = "Набор разделочных досок",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Этот кулон с цветком изготовлен с любовью и вниманием к деталям. Он станет великолепным подарком для вашей любимой. Уникальный дизайн и качественные материалы делают этот кулон украшением, которое будет радовать вас долгое время.",
                            ImageFileName = "epoxy-pendant.jpg",
                            Name = "Кулон с цветком",
                            Price = 1599m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Это кольцо из эпоксидной смолы – это искусство на вашем пальце. Уникальный дизайн и качественное исполнение делают его прекрасным аксессуаром для вашего образа. Подчеркните свою индивидуальность с этим кольцом.",
                            ImageFileName = "epoxy-ring.jpg",
                            Name = "Кольцо из эпоксидной смолы",
                            Price = 599m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Эта ваза 'Всплеск' – это настоящее произведение искусства. Изготовлена из эпоксидной смолы, она прекрасно дополнит интерьер вашего дома. Уникальный дизайн делает ее идеальным элементом декора и подарком.",
                            ImageFileName = "epoxy-vase.jpg",
                            Name = "Ваза 'Всплеск'",
                            Price = 4499m
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Этот набор статуэток из дерева вдохновлен древней мифологией. Каждая статуэтка сделана с большой любовью и вниманием к деталям. Он станет прекрасным украшением вашего дома и уникальным подарком для коллекционеров.",
                            ImageFileName = "idol-set.jpg",
                            Name = "Набор статуэток из дерева",
                            Price = 2199m
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Эта статуэтка 'Перун' изготовлена из дерева с особым вниманием к деталям. Она символизирует мощь и силу. Поместите эту статуэтку в свой дом, чтобы придать ему дополнительную атмосферу и символизировать свои убеждения.",
                            ImageFileName = "wooden-perun-idol.jpg",
                            Name = "Статуэтка 'Перун'",
                            Price = 1599m
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Эта статуэтка 'Воин' изготовлена из дерева и символизирует силу и защиту. Ее уникальный дизайн и качественные материалы делают ее идеальным подарком для любителей истории и мифологии.",
                            ImageFileName = "wooden-perun-idol-1.jpg",
                            Name = "Статуэтка 'Воин'",
                            Price = 1899m
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Эти деревянные часы 'Волны' принесут нотку морской атмосферы в ваш дом. Их уникальный дизайн и тщательная работа над деталями делают их идеальными как функциональным элементом интерьера и подарком для любителей моря.",
                            ImageFileName = "wooden-clock-waves.jpg",
                            Name = "Часы 'Волны'",
                            Price = 3099m
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Картина 'Абстракция' – это произведение современного искусства. Ее яркие цвета и абстрактный дизайн могут стать украшением вашей стены. Она поднимет настроение и добавит креативности в ваш дом.",
                            ImageFileName = "picture.jpg",
                            Name = "Картина 'Абстракция'",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Эти деревянные часы представляют собой идеальное сочетание функциональности и элегантного дизайна. Они прекрасно впишутся в любой интерьер и помогут вам следить за временем с толком.",
                            ImageFileName = "wooden-clock.jpg",
                            Name = "Деревянные часы",
                            Price = 2299m
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Эти деревянные часы со смолой являются настоящим произведением искусства. Их уникальный дизайн и комбинация дерева с эпоксидной смолой делают их прекрасным дополнением к вашему интерьеру и удивительным подарком для близких.",
                            ImageFileName = "wooden-clock-epoxy.jpg",
                            Name = "Деревянные часы со смолой",
                            Price = 2899m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
